[build]
  command = "npm run build"
  publish = ".next"

# This plugin is required for Next.js advanced features on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Ensures the build uses the correct Node version
  NODE_VERSION = "20"
